name: Create Release

on:
  push:
    tags:
      - '*'

env:
  RELEASE_BINARY_NAME: myapp

jobs:
  build-and-release:
    name: Build and Release Rust Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Rust Binary
        run: cargo build --release

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            ./target/release/${{ env.RELEASE_BINARY_NAME }}
