name: "release"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_release:
  
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      
      - name: "Build & test"
        run: cargo build --verbose --release
      
      - name: Release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          draft: false
          title: "Production Build"
          files: |
            ./target/release/kill_port
